### ISSUE TITLE
Image element size formatting issue

### ISSUE THREAD

**Issue by christian-git-md** [meridius/confluence-to-markdown#9]
Hi there,
thanks for your script, it fixes most of the problems i had with other implementations i tried.
I only had one issue: Images that have specified sizes come out as e.g.
```![](images/image.gif){width="8" height="8"}```
which is supported by any markdown version I could find. It would be nice if this was formatted to be more compatible with general markdown.

**Comment by meridius** [comment]
Hi @test-md I'm not actively using this script, so its development is not on my priority list anymore. You're however more than welcome to create PR for any features you deem necessary.
Cheers
